parts/app/advisor/urls.py
from django.urls import path, re_path

from parts.app.views import advisor


app_name = "advisor"

urlpatterns = [
    path("", advisor.AdvisorTemplateView.as_view(), name="advisor_index"),
    path("create", advisor.AdvisorCreateView.as_view(), name="advisor_create"),
    path(
        "update/<int:pk>",
        advisor.AdvisorUpdateView.as_view(),
        name="advisor_update_view",
    ),
    path(
        "show/<int:pk>", advisor.AdvisorDetailView.as_view(), name="advisor_read_view"
    ),
]

parts/app/arrival/urls.py
from django.urls import path
from django.utils.translation import ugettext_lazy as _

from parts.app.views import arrival

app_name = "arrival"

urlpatterns = [
    path("list", arrival.PartsArrivalListView.as_view(), name="arrival_index"),
    path("create", arrival.PartsArrivalCreateView.as_view(), name="arrival_create"),
    path(
        "update/<int:pk>", arrival.PartsArrivalUpdateView.as_view(), name="arrival_edit"
    ),
    path(
        "show/<int:pk>", arrival.PartsArrivalDetailView.as_view(), name="arrival-read"
    ),
]

parts/app/home/urls.py
from django.urls import path, include


from parts.app.views.home import HomeTemplateView
from parts.app.views.accounts import AccountLoginView

app_name = "home"

urlpatterns = [
    path("", AccountLoginView.as_view(), name="home_template_view"),
]

parts/app/partsnumber/urls.py
from django.urls import path, include

from parts.app.views import partsnumber, item_class

app_name = "partsnumber"

urlpatterns = [
    # Parts Pattern
    path(
        "", partsnumber.PartNumberTemplateView.as_view(), name="parts_number_index_view"
    ),
    path(
        "create",
        partsnumber.PartNumberCreateView.as_view(),
        name="parts_number_create_view",
    ),
    path(
        "update/<int:pk>",
        partsnumber.PartNumberUpdateView.as_view(),
        name="parts_number_update_view",
    ),
    path(
        "show/<int:pk>",
        partsnumber.PartsNumberDetailView.as_view(),
        name="parts_number_read_view",
    ),
    path(
        "delete/<int:pk>",
        partsnumber.PartnumberDeleteView.as_view(),
        name="parts_number_delete_view",
    ),
    # Unit of Measure Pattern
    path(
        "create/um",
        partsnumber.UnitofMeasureCreateView.as_view(),
        name="parts_um_create_view",
    ),
    # Item Class Pattern
    path(
        "list",
        item_class.PartnumberClassTemplateView.as_view(),
        name="parts_show_class",
    ),
    path(
        "create/class",
        item_class.PartnumberClassCreateView.as_view(),
        name="part_class_create_view",
    ),
    path(
        "update/<int:pk>/class",
        item_class.PartnumberClassUpdateView.as_view(),
        name="part_class_update_view",
    ),
    path(
        "read/<int:pk>/class",
        item_class.PartsNumberClassDetailView.as_view(),
        name="item_class_read",
    ),
    path("search", partsnumber.SearchView.as_view(), name="search_query"),
]

parts/config/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include("parts.app.home.urls")),

    path("dashboard/", include("parts.app.dashboard.urls")),

    path("accounts/", include("parts.app.accounts.urls")),

    path("accounts/", include("django.contrib.auth.urls")),

    path("partsnumber/", include("parts.app.partsnumber.urls")),

    path("advisor/", include("parts.app.advisor.urls")),

    path("arrival/", include("parts.app.arrival.urls")),

    path("__debug__", include(debug_toolbar.urls)),  # Debug purposes

    # Restframework
    path("api-auth/", include("rest_framework.urls")),
]

parts/app/accounts/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser, UserManager
from parts.core.models import TimeStampModel

class CustomUserManager(UserManager):
    pass


class CustomUser(AbstractUser):
    objects = CustomUserManager()

    @property
    def get_user_account_name(self):
        return "%s %s" % (self.first_name, self.last_name)

    @property
    def get_user_email(self):
        return self.email

class ProfileUser(TimeStampModel, models.Model):

    USER_LEVEL = (
        ("1", "Manager"),
        ("2", "Partsman"),
        ("3", "Warehouseman")
    )

    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    user_level = models.CharField(max_length=200, verbose_name=_("User Level"), choices=USER_LEVEL)

    def __str__(self):
        return "{0} {1}".format(self.user, self.user_level)

parts/app/advisor/models.py
from django.db import models

from django.utils.translation import ugettext_lazy as _
from parts.core.models import TimeStampModel
from parts.core.managers import AbstractUpdateViewManager


class ServiceAdvisor(AbstractUpdateViewManager, TimeStampModel):

    DESIGNATION = [("SVC", "Service Advisor"), ("BRPSVC", "Service Advisor BRP")]

    first_name = models.CharField(
        max_length=200, verbose_name=_("First Name"), blank=False, unique=True
    )

    last_name = models.CharField(
        max_length=200, verbose_name=_("Last Name"), blank=False
    )

    designation = models.CharField(
        max_length=200, verbose_name=_("Designation"), choices=DESIGNATION
    )

    class Meta:
        db_table = _("service_advisor")
        verbose_name = _("Service Advisor")
        verbose_name_plural = _("Services Advisors")
        ordering = ["id"]

    def __str__(self):
        return "{0} {1}".format(self.first_name, self.last_name)

parts/app/accounts/forms.py
from django.contrib.auth import forms

from parts.app.accounts.models import CustomUser


class CustomUserCreationForm(forms.UserCreationForm):
    class Meta(forms.UserCreationForm.Meta):
        model = CustomUser
        fields = forms.UserCreationForm.Meta.fields


class CustomUserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm):
        model = CustomUser
        # fields = UserChangeForm.Meta.fields
        fields = ["username", "first_name", "last_name", "email"]

    def __init__(self, *args, **kwargs):
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)
        instance = getattr(self, "instance", None)
        if instance and instance.id:
            self.fields["username"].widget.attrs["readonly"] = True


class AccountPasswordResetForm(forms.PasswordResetForm):
    class Meta(forms.PasswordResetForm):
        model = CustomUser


class AccountPasswordChangeForm(forms.PasswordChangeForm):
    class Meta(forms.PasswordChangeForm):
        model = CustomUser


class AccountSetPasswordForm(forms.SetPasswordForm):
    class Meta(forms.SetPasswordForm):
        model = CustomUser

parts/app/dashboard/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from parts.app.partsnumber.models import PartsNumber
from parts.app.advisor.models import ServiceAdvisor
from parts.app.arrival.models import PartsArrival
class DashboardTemplateView(TemplateView):
    pass

parts/app/views/accounts.py
from django.views import generic
from django.contrib.auth import views
from django.urls import reverse_lazy
from django.contrib.auth import views 

from parts.app.accounts import forms
from parts.app.accounts.models import CustomUser
from parts.app.mixins.common_mixins import AccountsMessageMixins


class AccountTemplateView(generic.TemplateView):
    template_name = "accounts/index.html"


class AccountLoginView(views.LoginView):
    template = "accounts/login.html"


# TODO
# Fix Logout that can use to redirect logout without authentication
class AccountLogoutView(views.LogoutView):
    template_name = "registration/logout.html"


class AccountEditView(AccountsMessageMixins, generic.UpdateView):
    template_name = "accounts/update_user.html"
    success_url = reverse_lazy("dashboard:dashboard_view_index")
    context_object_name = "user"
    messages = 'updated'
    form_class = forms.CustomUserChangeForm

    def get_object(self, query_pk_and_slug=None):
        user = CustomUser.objects.filter(id=self.kwargs["pk"]).first()
        return user


# TODO fix bug updating password from other account
class AccountChangePasswordView(views.PasswordChangeView):
    template_name = "accounts/password_change.html"
    success_url = reverse_lazy("accounts:edit_user")
    form_class = forms.AccountPasswordChangeForm

parts/app/views/advisor.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import renderers
from rest_framework import generics

from parts.app.advisor.models import ServiceAdvisor
from parts.core.forms import AdvisorForm
from parts.app.mixins.common_mixins import ServiceAdvisorMixins


class AdvisorTemplateView(ServiceAdvisorMixins, generic.ListView):
   template_name = "advisor/index.html"
   model = ServiceAdvisor
   queryset = ServiceAdvisor.objects.all()
   paginate_by = 2
   #context_object_name = "advisor"
    
    
class AdvisorCreateView(ServiceAdvisorMixins, generic.CreateView):
    template_name = "advisor/add_advisor.html"
    form_class = AdvisorForm
    messages = 'added'
    success_url = reverse_lazy("advisor:advisor_index")

    def get_context_data(self, **kwargs):
        context = super(AdvisorCreateView, self).get_context_data(**kwargs)
        context["advisor"] = ServiceAdvisor.objects.all()
        return context


class AdvisorUpdateView(ServiceAdvisorMixins, generic.UpdateView):
    template_name = "advisor/add_advisor.html"
    form_class = AdvisorForm
    model = ServiceAdvisor
    messages = 'updated'
    success_url = reverse_lazy("advisor:advisor_index")

    def get_object(self):
        return super(AdvisorUpdateView, self).get_object()


class AdvisorDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "advisor/read_advisor.html"
    model = ServiceAdvisor
    context_object_name = "advisor"

    def get_object(self, query_pk_and_slug=None):
        advisor = ServiceAdvisor.objects.all().filter(id=self.kwargs["pk"]).first()
        return advisor

parts/app/views/arrival.py
from django.views import generic
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.mixins import LoginRequiredMixin

from parts.app.arrival.models import PartsArrival
from parts.core.forms import PartsArrivalForm
from parts.app.mixins.common_mixins import PartsArrivalMixins


class PartsArrivalListView(PartsArrivalMixins, generic.ListView):
    template_name = "arrival/index.html"
    model = PartsArrival
    paginate_by = 3


class PartsArrivalCreateView(PartsArrivalMixins, generic.CreateView):
    template_name = "arrival/add_arrival.html"
    form_class = PartsArrivalForm
    success_url = reverse_lazy("arrival:arrival_create")
    messages = "added"

    def get_context_data(self, **kwargs):
        context = super(PartsArrivalCreateView, self).get_context_data(**kwargs)
        context["arrival"] = PartsArrival.objects.all()
        return context



class PartsArrivalUpdateView(PartsArrivalMixins,generic.UpdateView):
    template_name = "arrival/add_arrival.html"
    form_class = PartsArrivalForm
    success_url = reverse_lazy("arrival:arrival_index")
    messages = "updated"

    def get_object(self, query_pk_and_slug=None):
        query = PartsArrival.objects.filter(id=self.kwargs["pk"]).first()
        return query

class PartsArrivalDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "arrival/read_view.html"
    model = PartsArrival
    context_object_name = "arrival"

    def get_object(self, query_pk_and_slug=None):
        query = PartsArrival.objects.filter(id=self.kwargs["pk"]).first()
        return query

parts/app/views/dashboard.py
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from parts.app.partsnumber.models import PartsNumber
from parts.app.arrival.models import PartsArrival
from parts.app.advisor.models import ServiceAdvisor


class DashboardViewsTemplate(LoginRequiredMixin, generic.TemplateView):
    template_name = 'dashboard/index.html'
    
    def get_context_data(self, **kwargs):
        context = super(DashboardViewsTemplate,
                        self).get_context_data(**kwargs)
        # Refactor the queryset
        context['partsnumber'] = PartsNumber.objects.values('id').count()
        context['arrival'] = PartsArrival.objects.values('id').count()
        context['complete'] = PartsArrival.objects.filter(
            remarks__contains='COMPLETED').count()
        context['not_complete'] = PartsArrival.objects.filter(
            remarks__contains='NOT COMPLETED').count()
        context['lacking'] = PartsArrival.objects.filter(
            remarks__contains='LACKING').count()
        context['service_advisor'] = ServiceAdvisor.objects.values('id').count()
        return context

parts/app/views/home.py
from django.urls import reverse_lazy
from django.views import generic


class HomeTemplateView(generic.TemplateView):
    template_name = "home/index.html"

parts/app/views/item_class.py
#  View Class for Partnumber and its description
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import ugettext_lazy as _

from parts.app.partsnumber.models import PartNumberClass
from parts.core.forms import PartNumberClassForm


class PartnumberClassTemplateView(generic.ListView):
    template_name = "item_class/index.html"
    model = PartNumberClass
    paginate_by = 2
    queryset = PartNumberClass.objects.all()


class PartnumberClassCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "item_class/add_class_partnumber.html"
    form_class = PartNumberClassForm
    success_url = reverse_lazy("partsnumber:parts_show_class")

    def get_context_data(self, **kwargs):
        context = super(PartnumberClassCreateView,
                        self).get_context_data(**kwargs)
        context["partnumber_class"] = PartNumberClass.objects.all()
        return context


class PartnumberClassUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "item_class/add_class_partnumber.html"
    form_class = PartNumberClassForm
    model = PartNumberClass
    success_url = reverse_lazy("partsnumber:parts_show_class")
    context_object_name = 'item_class'

    def get_first_object(self):
        return super(PartnumberClassUpdateView, self).get_first_object()


class PartsNumberClassDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "item_class/read_item_class.html"
    model = PartNumberClass
    context_object_name = 'item_class'

    def get_first_object(self):
        return super(PartnumberClassUpdateView, self).get_first_object()

parts/app/views/partsnumber.py
from django.views import generic
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.db.models import Q

from parts.app.mixins.common_mixins import PartsNumberMixin
from parts.app.partsnumber.models import PartsNumber, UnitMeasure
from parts.core.forms import (
        PartsNumberForm,
        UnitofMeasureForm,
        PartNumberClassForm
)

class PartNumberTemplateView(generic.ListView):
    template_name = "partsnumber/index.html"
    model = PartsNumber
    paginate_by = 10
    context_object_name = "partsnumber"


class PartNumberCreateView(PartsNumberMixin, generic.CreateView):
    template_name = "partsnumber/add_partnumber.html"
    model = PartsNumber
    form_class = PartsNumberForm
    messages = "added"
    success_url = reverse_lazy("partsnumber:parts_number_create_view")

    def get_context_data(self, **kwargs):
        context = super(PartNumberCreateView, self).get_context_data(**kwargs)
        context["partsnumber_id"] = PartsNumber.objects.all()
        return context
    
    
class PartsNumberDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "partsnumber/read_partnumber.html"
    model = PartsNumber
    context_object_name = "partsnumber"

    def get_object(self):
        return super(PartsNumberDetailView, self).get_object()


class PartNumberUpdateView(PartsNumberMixin, generic.UpdateView):
    template_name = "partsnumber/add_partnumber.html"
    form_class = PartsNumberForm
    success_url = reverse_lazy("partsnumber:parts_number_index_view")
    model = PartsNumber
    messages = "updated"
    context_object_name = "partsnumber"

    def get_object(self):
        return super(PartNumberUpdateView, self).get_object()


class PartnumberDeleteView(PartsNumberMixin, generic.DeleteView):
    template_name = "partsnumber/confirm_delete.html"
    success_url = reverse_lazy("partsnumber:parts_number_index_view")
    model = PartsNumber
    context_object_name = "partsnumber"

    def get_object(self):
        return super(PartnumberDeleteView, self).get_object()


class SearchView(LoginRequiredMixin, generic.ListView):
    template_name = "partsnumber/search_results.html"
    model = PartsNumber

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = PartsNumber.objects.filter(
            Q(partnumber__icontains=query) | Q(description__icontains=query)
        )
        return object_list


class UnitofMeasureCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "partsnumber/unit_of_measure.html"
    model = UnitMeasure
    form_class = UnitofMeasureForm
    success_url = reverse_lazy("partsnumber:parts_um_create_view")

parts/templates/advisor/add_advisor.html
{% extends "common/base.html" %}
{% load i18n bootstrap4 %}

{% block title %} Add Service Advisor {% endblock title %}
{% block navbar %} {% include "common/includes/navbar.html" %} {% endblock navbar %}
{% block sidebar %} {% include "common/includes/sidebar.html" %} {% endblock sidebar %}
{% block messages %} {% include "common/includes/message.html" %}{% endblock messages %}

{% block main %}
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
             <h1 class="m-0"><b>{% trans "Service Advisor" %}</b></h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item">
                <a href="#">{% trans "Home" %}</a>
                </li>
                <li class="breadcrumb-item active">
                <a href="#">{% trans "Service Advisor" %}</a>
                </li>
            </ol>
        </div>
    </div>
</div>
</section>
<section class="content">
<div class="container-fluid">
    <div class="card card-default">
        <div class="card-body">
           <form action="" method="POST">
                {% csrf_token %}
                {% bootstrap_form form  %}
                    {% if advisor is not None %}
                        <div class="col">
                            <label for=""></label>
                            <button type="submit" class="btn btn-primary btn-block" id="submit-button">{% trans "Save" %}</button>
                        </div>
                    {% else %}
                        <div class="col">
                            <label for=""></label>
                            <button type="submit" class="btn btn-success btn-block" id="submit-button">{% trans "Update" %}</button>
                        </div>
                    {% endif %}
                <div class="col">
                    <label for=""></label>
                    <a href="{% url 'advisor:advisor_index' %}" class="btn btn-danger btn-block">{% trans "Cancel" %}</a>
                </div>
         </div>
            </form>
    </div>
</div>
</section>
{% endblock main %}

parts/templates/advisor/index.html
{% extends "common/base.html" %}
{% load humanize i18n bootstrap4 %}

{% block navbar %} {% include "common/includes/navbar.html" %} {% endblock navbar %}
{% block sidebar %} {% include "common/includes/sidebar.html" %} {% endblock sidebar %}
{% block messages %} {% include "common/includes/message.html" %} {% endblock messages %}

{% block main %}
    {% include "common/modal/_modal.html" %}
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
             <h1 class="m-0"><b>{% trans "Service Advisor" %}</b></h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item">
                <a href="#">{% trans "Home" %}</a>
                </li>
                <li class="breadcrumb-item active">
                <a href="#">{% trans "Service Advisor" %}</a>
                </li>
            </ol>
        </div>
    </div>
</div>
</section>
<section class="content">
<div class="container-fluid">
    <div class="card card-default">
        <div class="card-body">
          <div class="row mb-2">
                    <div class="col-sm-6">
                    </div>
                    <div class="col-sm-6">
                    <a href="{% url 'advisor:advisor_create' %}" class="btn btn-danger btn-sm float-sm-right">
                    {% trans "Add Advisor" %}
                        <i class="fas fa-plus" aria-hidden="true"></i>
                    </button>
                    </a>
                    </div>
                </div>
            <table class="table table-bordered xs-data-table">
                <thead class="thead-dark">
                    <tr>
                        {% comment %} <th>Employee ID</th> {% endcomment %}
                        <th>{% trans "First Name" %}</th>
                        <th>{% trans "Last Name" %}</th>
                        <th>{% trans "Designation" %}</th>
                        <th>{% trans "Actions" %}</th>
                    </tr>
                </thead>
                <tbody>

                        {% for service_advisor in page_obj.object_list  %}
                    <tr>
                        <td>{{ service_advisor.first_name }}</a></b></td>
                        <td>{{ service_advisor.last_name }}</td>
                        <td>{{ service_advisor.designation }}</td>
            <td><a href="{% url 'advisor:advisor_update_view' pk=service_advisor.id %}" 
                    class="btn btn-primary btn-xs edit-users">
                <i class="fas fa-pencil-alt" aria-hidden="true"></i>
            </a>
            <button type="button" class="btn btn-danger btn-xs read-advisor" 
                data-id = "{% url 'advisor:advisor_read_view' pk=service_advisor.id %}"
            data-toggle="modal" data-target="#modal">
                <i class="fas fa-eye" aria-hidden="true"></i>
            </button>
            </td>
                </tr>
                {% empty %}
                            <p class="font-weight-bold">{% trans "No advisor has been maintained try adding" %} 
                            <a href="{% url 'partsnumber:parts_number_create_view'%}">{% trans "here" %}</a></p>
                            <p class="mb-0"></p>
                        {% endfor %}

                </tbody>
            </table>
        <div>
    </div>
</div>
</div>
</section>
    {% include "common/includes/paginator.html" %}
{% endblock main %}

parts/templates/advisor/read_advisor.html
{% load static humanize i18n %}

<div class="modal-header">
    <h3 class="modal-title">{% trans "Parts Advisor Details" %}</h3>
    <button type="button" data-dismiss="modal" class="close" aria-label="Close">
        <span aria-hidden="close">&times;</span>
    </button>
</div>
<div class="modal-body">
    <ul class="list-group">
        <li class="list-group-item">{% trans "First Name" %}: <b>{{advisor.first_name}}</b></li>
        <li class="list-group-item">{% trans "Last Name" %}: <b>{{advisor.last_name }}</b></li>
        <li class="list-group-item">{% trans "Designation" %}: <b>{{advisor.designation}}</b></li>
        <li class="list-group-item">{% trans "Date Created" %}: <b>{{advisor.created_at}}</b></li>
        <li class="list-group-item">{% trans "Date Updated" %}: <b>{{advisor.updated_at}}</b></li>

    </ul>
</div>


{% include 'common/modal/_modal_footer.html' %}